set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER "$ENV{CC}")
set(CMAKE_CXX_COMPILER "$ENV{CXX}")
set(CMAKE_AR "$ENV{AR}")
set(CMAKE_RANLIB "$ENV{RANLIB}")
set(CMAKE_STRIP "$ENV{STRIP}")
set(CMAKE_SYSROOT "$ENV{HISTB_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH
  "$ENV{HISTB_ES_PREFIX}"
  "$ENV{HISTB_OUT_ROOT}"
  "$ENV{HISTB_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
